-- MaintainOS initial schema
-- Store codes are numeric per country (e.g. 172).
-- Each country has its own WhatsApp Business number (phone_number_id).

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Hierarchy
-- ---------------------------------------------------------------------------

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table public.countries (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  code text not null, -- IL, FR, ...
  name text not null,
  default_locale text not null default 'he',
  -- Meta WhatsApp line for this country (one number per country)
  whatsapp_phone_number_id text,
  whatsapp_display_phone text,
  whatsapp_access_token text,
  created_at timestamptz not null default now(),
  unique (organization_id, code)
);

create table public.regions (
  id uuid primary key default gen_random_uuid(),
  country_id uuid not null references public.countries(id) on delete cascade,
  code text not null,
  name text not null,
  created_at timestamptz not null default now(),
  unique (country_id, code)
);

create table public.stores (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  country_id uuid not null references public.countries(id) on delete cascade,
  region_id uuid not null references public.regions(id) on delete cascade,
  code text not null, -- "172" unique within country
  name text not null,
  address text,
  city text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (country_id, code)
);

create index stores_org_idx on public.stores (organization_id);
create index stores_country_code_idx on public.stores (country_id, code);

create table public.assets (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  code text not null,
  name text not null,
  asset_type text not null default 'other',
  created_at timestamptz not null default now(),
  unique (store_id, code)
);

-- ---------------------------------------------------------------------------
-- Identity / RBAC (skeleton for Phase 0+)
-- ---------------------------------------------------------------------------

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  email text,
  phone text,
  locale text not null default 'he',
  created_at timestamptz not null default now()
);

create type public.member_role as enum (
  'global_admin',
  'global_maintenance',
  'country_manager',
  'regional_manager',
  'store_manager',
  'store_employee',
  'internal_technician',
  'external_provider'
);

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  role public.member_role not null,
  country_id uuid references public.countries(id) on delete cascade,
  region_id uuid references public.regions(id) on delete cascade,
  store_id uuid references public.stores(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index memberships_profile_idx on public.memberships (profile_id);

-- ---------------------------------------------------------------------------
-- Tickets
-- ---------------------------------------------------------------------------

create type public.ticket_status as enum (
  'new',
  'triaged',
  'assigned',
  'in_progress',
  'waiting_parts',
  'resolved',
  'closed',
  'cancelled'
);

create type public.ticket_priority as enum (
  'critical',
  'high',
  'medium',
  'low'
);

create type public.ticket_source as enum (
  'whatsapp',
  'qr_whatsapp',
  'nfc_whatsapp',
  'web_fallback',
  'demo'
);

create table public.tickets (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  country_id uuid not null references public.countries(id) on delete cascade,
  region_id uuid not null references public.regions(id) on delete cascade,
  store_id uuid not null references public.stores(id) on delete cascade,
  asset_id uuid references public.assets(id) on delete set null,
  number bigint generated by default as identity,
  display_number text, -- e.g. OC-18342 derived
  category text not null default 'other',
  priority public.ticket_priority not null default 'medium',
  status public.ticket_status not null default 'new',
  title text,
  description text not null default '',
  source public.ticket_source not null default 'whatsapp',
  reporter_phone text,
  reporter_name text,
  language text not null default 'he',
  assigned_to uuid references public.profiles(id) on delete set null,
  sla_respond_by timestamptz,
  sla_resolve_by timestamptz,
  resolved_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, number)
);

create index tickets_store_status_idx on public.tickets (store_id, status);
create index tickets_org_created_idx on public.tickets (organization_id, created_at desc);
create index tickets_status_priority_idx on public.tickets (status, priority);

create table public.ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  channel text not null default 'whatsapp',
  direction text not null check (direction in ('inbound', 'outbound', 'system')),
  body text,
  wa_message_id text unique,
  media_url text,
  raw jsonb,
  created_at timestamptz not null default now()
);

create table public.ticket_attachments (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  url text not null,
  kind text not null default 'image',
  created_at timestamptz not null default now()
);

create table public.ticket_events (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  event_type text not null,
  actor_id uuid references public.profiles(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index ticket_events_ticket_idx on public.ticket_events (ticket_id, created_at);

-- Short-lived WhatsApp intake sessions (store identified via QR/NFC/code)
create table public.intake_sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  country_id uuid not null references public.countries(id) on delete cascade,
  wa_id text not null,
  store_id uuid references public.stores(id) on delete set null,
  store_code text,
  state text not null default 'awaiting_store', -- awaiting_store | awaiting_description | done
  pending_description text,
  expires_at timestamptz not null default (now() + interval '30 minutes'),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (country_id, wa_id)
);

create table public.processed_webhooks (
  id uuid primary key default gen_random_uuid(),
  message_id text not null,
  country_id uuid references public.countries(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (message_id, country_id)
);

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger tickets_set_updated_at
before update on public.tickets
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS skeleton (service role bypasses; tighten in later migrations with auth)
-- ---------------------------------------------------------------------------

alter table public.organizations enable row level security;
alter table public.countries enable row level security;
alter table public.regions enable row level security;
alter table public.stores enable row level security;
alter table public.assets enable row level security;
alter table public.profiles enable row level security;
alter table public.memberships enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_messages enable row level security;
alter table public.ticket_attachments enable row level security;
alter table public.ticket_events enable row level security;
alter table public.intake_sessions enable row level security;
alter table public.processed_webhooks enable row level security;

-- Temporary authenticated read for HQ bootstrap (will scope by memberships later)
create policy org_read_authenticated on public.organizations
  for select to authenticated using (true);

create policy countries_read_authenticated on public.countries
  for select to authenticated using (true);

create policy regions_read_authenticated on public.regions
  for select to authenticated using (true);

create policy stores_read_authenticated on public.stores
  for select to authenticated using (true);

create policy tickets_read_authenticated on public.tickets
  for select to authenticated using (true);

create policy tickets_update_authenticated on public.tickets
  for update to authenticated using (true);

create policy ticket_messages_read_authenticated on public.ticket_messages
  for select to authenticated using (true);

create policy ticket_events_read_authenticated on public.ticket_events
  for select to authenticated using (true);

create policy assets_read_authenticated on public.assets
  for select to authenticated using (true);
